const fs=require('fs'),vm=require('vm'),assert=require('assert');let data={},elements={};const el=()=>({innerHTML:'',textContent:'',style:{},dataset:{},disabled:false,classList:{remove(){},add(){},toggle(){}},setAttribute(){},appendChild(){},remove(){},addEventListener(){}});const context={console,document:{getElementById(id){return elements[id]||(elements[id]=el())},querySelector(){return el()},querySelectorAll(){return []},createElement(){return el()},body:el(),addEventListener(){}},localStorage:{getItem(k){return data[k]||null},setItem(k,v){data[k]=v}},setTimeout(){return 1},clearTimeout(){},setInterval(){return 1},clearInterval(){},window:{},navigator:{},location:{protocol:'file:'},Math,Date,Set};vm.createContext(context);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../app.js'),'utf8'),context);const run=s=>vm.runInContext(s,context);
for(const [a,b,i]of [[0,1,3],[1,2,4],[2,0,5]]){assert.equal(run(`pair(${a},${b})[2]`),i);assert.equal(run(`pair(${b},${a})[2]`),i)}
assert.equal(run('colorMix([1,1,0]).name'),'Naranja');assert.equal(run('colorMix([0,1,1]).name'),'Verde');assert.equal(run('colorMix([1,0,1]).name'),'Violeta');assert.equal(run('colorMix([3,1,0]).name'),'Naranja rojizo');assert.equal(run('colorMix([1,3,0]).name'),'Naranja amarillento');assert.equal(run('colorMix([1,1,1]).name'),'Marrón');assert.equal(run('colorMix([0,0,0])'),null);
assert.equal(run('available(2)'),false);run('openLesson(1);touchPrimary(0);touchPrimary(1);touchPrimary(2)');assert.equal(run('primSeen.size'),3);
run('startQuiz(1,0)');run('answer((expected()+1)%3)');assert.equal(run('S.correct'),0);for(let i=0;i<5;i++){run('answer(expected());continueQuiz()')}assert.equal(run('S.correct'),5);assert.equal(run('S.attempts'),6);assert.equal(run('available(2)'),true);
run('openLesson(2);lessonMix();changeLesson(1);lessonMix();changeLesson(1);lessonMix();changeLesson(1)');assert.equal(run('S.found.length'),3);assert.equal(run('available(3)'),true);
for(let m=0;m<4;m++){run(`startQuiz(3,${m})`);for(let i=0;i<5;i++)run('answer(expected());continueQuiz()')}
assert.equal(run('available(4)'),true);run('openLesson(4);showProportion(1);showProportion(7)');assert.equal(run('propSeen.size'),3);run('nextProportion();showProportion(1);showProportion(7);nextProportion();showProportion(1);showProportion(7);nextProportion()');assert.equal(run('q.type'),5);for(let i=0;i<5;i++)run('answer(expected());continueQuiz()');assert.equal(run('available(5)'),true);
run('startQuiz(5,4)');for(let i=0;i<5;i++)run('answer(expected());continueQuiz()');assert.equal(run('S.done.length'),5);
run("go('lab');addDrop(0);addDrop(1);labMix();undoDrop()");assert.equal(run('amount[1]'),0);run("go('home');go('lab');undoDrop()");assert.equal(run('amount.join()'),'0,0,0');
let saved=JSON.parse(data['paleta-pintor.progreso.v1']);assert.equal(saved.done.length,5);assert.equal(saved.found.length,3);assert(saved.correct>20);console.log('PASS: mixtures, ratios, all quiz modes, mistakes, five unlocks, discoveries, undo, persistence');

for(let i=0;i<16;i++){run(`go('painter');loadPreset(${i})`);assert.equal(run('paints.length'),8);assert.equal(run('percentages(paints).reduce((s,n)=>s+n,0)'),100);assert.equal(run('painterMix(paints).hex'),run(`painterMix(PRESETS[${i}].a).hex`));}
run("go('painter');clearPaint()");assert.equal(run('painterMix(paints).hex'),null);for(let i=0;i<8;i++){run(`setPaint(${i},100)`);assert(run('painterMix(paints).hex').match(/^#[0-9a-f]{6}$/));}run('setPaint(6,0);setPaint(7,0)');assert.equal(run('presetIndex'),-1);assert.equal(JSON.parse(data['paleta-pintor.paleta.v1']).length,8);assert.equal(run('painterMix([0,0,0,100,0,0,0,0]).hex'),run('painterMix([50,50,0,0,0,0,0,0]).hex'));console.log('PASS: all 16 presets, 8 sliders, 100% distribution, secondary decomposition and palette persistence');
