'use strict';
const C=[{name:'Rojo',hex:'#e74750',symbol:'●'},{name:'Amarillo',hex:'#f3ca30',symbol:'▲'},{name:'Azul',hex:'#3977d5',symbol:'■'},{name:'Naranja',hex:'#f18a35'},{name:'Verde',hex:'#4ca766'},{name:'Violeta',hex:'#9256b4'}];
const REC=[[0,1,3],[1,2,4],[2,0,5]], TITLES=['Primarios','Secundarios','Mezclas','Proporciones','Reto de colores'];
let S;try{S=JSON.parse(localStorage.getItem('paleta-pintor.progreso.v1'))}catch{} S=Object.assign({done:[],found:[],correct:0,attempts:0,best:0,streak:0,sound:true},S||{});
let page='home',lesson=0,pick=[],amount=[0,0,0],mode=0,level=1,q=null,round=0,sessionCorrect=0,timer=null,advance=null,deadline=0,locked=false,lessonSeen=new Set(),primSeen=new Set(),propSeen=new Set();
const $=id=>document.getElementById(id), save=()=>localStorage.setItem('paleta-pintor.progreso.v1',JSON.stringify(S));
function sound(win=false){if(!S.sound)return;try{let a=window.audio||(window.audio=new (window.AudioContext||window.webkitAudioContext)());a.resume();[win?523:392,win?659:440,win?784:523].forEach((f,i)=>{let o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=f;g.gain.setValueAtTime(.045,a.currentTime+i*.085);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+i*.085+.12);o.start(a.currentTime+i*.085);o.stop(a.currentTime+i*.085+.13)})}catch{}}
function say(text){if(!S.sound)return;if(window.Narrator)window.Narrator.say(text);else if(window.speechSynthesis){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='es-ES';speechSynthesis.speak(u)}}
function reward(text){sound(true);say(text);let e=document.createElement('div');e.className='star';e.textContent='⭐';document.body.appendChild(e);setTimeout(()=>e.remove(),900)}
function sw(i,fn,selected=false){return `<button class="swatch ${selected?'selected':''}" onclick="${fn}" aria-label="${C[i].name}${selected?', seleccionado':''}" aria-pressed="${selected}"><span class="dot" style="--c:${C[i].hex}"></span>${C[i].name}</button>`}
function header(title){return `<header><button onclick="back()" aria-label="Volver">← Volver</button><span class="tag">${title}</span><button onclick="toggleSound()" aria-label="${S.sound?'Silenciar':'Activar sonido'}">${S.sound?'♪':'♪̸'}</button></header>`}
function toggleSound(){S.sound=!S.sound;save();if(!S.sound&&window.speechSynthesis)speechSynthesis.cancel();let b=document.querySelector('header button:last-child');if(b){b.textContent=S.sound?'♪':'♪̸';b.setAttribute('aria-label',S.sound?'Silenciar':'Activar sonido')}}
function cancel(){clearInterval(timer);clearTimeout(advance);timer=null;advance=null;locked=false}
function go(p){cancel();page=p;pick=[];if(p==='home')home();if(p==='learn')learn();if(p==='lab'){amount=[0,0,0];history=[];lab()}if(p==='games')games();if(p==='achievements')achievements();if(p==='map')map();if(p==='painter')painter();document.body.dataset.page=p;updateNav();}
function back(){if(page==='home')return;if(page==='quiz')go('games');else if(page==='lesson'||page==='map')go('learn');else go('home')}
function home(){$('app').innerHTML=`<header><span class="tag">Pequeños descubrimientos</span><button onclick="toggleSound()" aria-label="Sonido">${S.sound?'♪':'♪̸'}</button></header><div class="hero center"><svg class="logo" viewBox="0 0 155 125" aria-hidden="true"><circle cx="48" cy="37" r="31" fill="#e74750"/><circle cx="107" cy="37" r="31" fill="#f3ca30"/><circle cx="78" cy="91" r="31" fill="#3977d5"/><path d="M44 22l10 -5M101 22l10 -5M73 76l10 -5" stroke="#ffffff88" stroke-width="7" stroke-linecap="round"/></svg><h1>Paleta pintor</h1><p class="sub">Mira. Experimenta. ¡Descubre!</p></div><div class="grid"><button class="tile" style="background:#fce4db" onclick="go('learn')"><i>🎨</i><b>Aprender</b><span>Paso a paso</span></button><button class="tile" style="background:#e5eee3" onclick="go('lab')"><i>🧪</i><b>Mezclar</b><span>Tu laboratorio</span></button><button class="tile" style="background:#e4eaf9" onclick="go('games')"><i>🎮</i><b>Jugar</b><span>Pequeños retos</span></button><button class="tile" style="background:#f5ebca" onclick="go('achievements')"><i>🏆</i><b>Mis logros</b><span>Lo que has aprendido</span></button></div><button class="tile painter-tile" onclick="go('painter')"><i>🖌️</i><div><b>Paleta del pintor</b><span>8 barras · 16 colores · Infinitas mezclas</span></div><strong>→</strong></button><p class="note center">Mezclas de pintura · Sin anuncios · Progreso en este navegador</p>`}
function available(n){return n===1||S.done.includes(n-1)}
function learn(){$('app').innerHTML=header('Aprender')+`<h1>Un color, una sorpresa</h1><p class="sub">Toca un nivel para empezar.</p>`+TITLES.map((t,i)=>`<button class="level" ${available(i+1)?'':'disabled'} onclick="openLesson(${i+1})"><span class="badge">${S.done.includes(i+1)?'⭐':available(i+1)?i+1:'🔒'}</span><span><b>${t}</b><small>${available(i+1)?'Mira, toca y descubre':'Completa el nivel anterior'}</small></span></button>`).join('')+`<button class="action" onclick="go('map')">Mapa de colores</button>`}
function openLesson(n){cancel();page='lesson';level=n;lesson=0;lessonSeen=new Set();primSeen=new Set();propSeen=new Set();showLesson()}
function complete(n){if(!S.done.includes(n)){S.done.push(n);save();reward('¡Nivel completado!')}go('learn')}
function showLesson(){if(level===1){$('app').innerHTML=header('Nivel 1')+`<h1>Los tres primarios</h1><p class="sub">Toca cada color. Son nuestra base.</p><div class="palette">${[0,1,2].map(i=>sw(i,`touchPrimary(${i})`,primSeen.has(i))).join('')}</div><div class="card center"><h2 id="primaryName">¡Explóralos!</h2><p>Con estos tres crearemos más colores.</p></div><button class="action" id="finish" ${primSeen.size===3?'':'disabled'} onclick="startQuiz(1,0)">Juega con los primarios →</button>`;return}
if(level===2||level===3){const r=REC[lesson];$('app').innerHTML=header(`Nivel ${level}`)+`<h1>${level===2?'Nacen nuevos colores':'Descubre la mezcla'}</h1><p class="sub">${level===2?'Toca «Mezclar» y observa.':'Toca dos colores para crear '+C[r[2]].name.toLowerCase()+'.'}</p>`+(level===2?recipe(r[0],r[1]):`<div class="palette">${[0,1,2].map(i=>sw(i,`lessonPick(${i})`)).join('')}</div>`)+`<div class="bowl" id="bowl"></div><div class="feedback" id="feedback" aria-live="polite">${level===3?C[r[2]].name:'¿Qué aparecerá?'}</div><button class="action" onclick="lessonMix()">Mezclar</button><div class="row"><button class="quiet" onclick="changeLesson(-1)" ${lesson===0?'disabled':''}>← Anterior</button><button class="quiet" id="next" onclick="changeLesson(1)" ${lessonSeen.has(lesson)?'':'disabled'}>${lesson===2?'Terminar →':'Siguiente →'}</button></div>`;return}
if(level===4){proportions();return}startQuiz(5,4)}
function touchPrimary(i){primSeen.add(i);showLesson();$('primaryName').textContent=C[i].name;say(C[i].name)}
function recipe(a,b,c){return `<div class="recipe">${sw(a,`say('${C[a].name}')`)}<b>+</b>${sw(b,`say('${C[b].name}')`)}${c===undefined?'':`<b>→</b>${sw(c,`say('${C[c].name}')`)}`}</div>`}
function lessonPick(i){if(pick.includes(i))pick=pick.filter(x=>x!==i);else if(pick.length<2)pick.push(i);document.querySelector('.palette').innerHTML=[0,1,2].map(j=>sw(j,`lessonPick(${j})`,pick.includes(j))).join('')}
function pair(a,b){return REC.find(r=>r.includes(a)&&r.includes(b)&&a!==b&&a<3&&b<3)}
function animate(values,hex){let bowl=$('bowl');if(!bowl)return;bowl.classList.remove('mix');void bowl.offsetWidth;bowl.classList.add('mix');bowl.style.background=hex;bowl.innerHTML=values.map((i,k)=>`<i class="drop" style="--c:${C[i].hex};--x:${25+k*35}%"></i>`).join('');sound()}
function discover(i){if(!S.found.includes(i)){S.found.push(i);save()}}
function lessonMix(){let r=REC[lesson];if(level===3&&!(pick.length===2&&pair(...pick)?.[2]===r[2])){$('feedback').textContent='Prueba otra combinación';say('Prueba otra combinación');return}animate(r.slice(0,2),C[r[2]].hex);lessonSeen.add(lesson);discover(r[2]);$('feedback').textContent='¡Has creado '+C[r[2]].name.toLowerCase()+'!';$('next').disabled=false;say($('feedback').textContent)}
function changeLesson(d){if(d===1&&lesson===2){if(level===2)complete(2);else startQuiz(3,0);return}lesson+=d;pick=[];showLesson()}
function lab(){$('app').innerHTML=header('Laboratorio')+`<h1>Tu mezcla, tu descubrimiento</h1><p class="sub">Toca o arrastra gotas al recipiente.</p><div class="palette">${[0,1,2].map(i=>sw(i,`addDrop(${i})`)).join('')}</div><div class="bowl" id="bowl" aria-label="Recipiente de mezcla"></div><div class="feedback" id="feedback" aria-live="polite">Elige tus colores</div><div id="amounts" class="center sub"></div><button class="action" onclick="labMix()">Mezclar</button><div class="row"><button class="quiet" onclick="undoDrop()">Quitar una gota</button><button class="quiet" onclick="resetLab()">Vaciar</button></div><p class="note center">Cada toque añade una gota. ¡Cambia las cantidades!</p>`;bindDrag();updateAmounts()}
let history=[];
function bindDrag(){document.querySelectorAll('.palette .swatch').forEach((el,i)=>{let start=null,moved=false;el.addEventListener('pointerdown',e=>{start={x:e.clientX,y:e.clientY};moved=false;el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>18)moved=true});el.addEventListener('pointerup',e=>{if(moved){let b=$('bowl').getBoundingClientRect();if(e.clientX>=b.left&&e.clientX<=b.right&&e.clientY>=b.top&&e.clientY<=b.bottom)addDrop(i);el.dataset.dragged='1';setTimeout(()=>delete el.dataset.dragged,100)}start=null});el.addEventListener('click',e=>{if(el.dataset.dragged)e.stopImmediatePropagation()},true);el.style.touchAction='none';el.setAttribute('draggable','true');el.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',i))});$('bowl').ondragover=e=>e.preventDefault();$('bowl').ondrop=e=>{e.preventDefault();const i=Number(e.dataTransfer.getData('text/plain'));if([0,1,2].includes(i))addDrop(i)}}
function addDrop(i){if(amount[i]>=8){$('feedback').textContent='Máximo 8 gotas de cada color';return}amount[i]++;history.push(i);updateAmounts();say(C[i].name)}
function updateAmounts(){$('amounts').innerHTML=amount.map((n,i)=>n?`<div>${C[i].name}: ${n}<div class="drops">${Array(n).fill(`<span class="tiny" style="--c:${C[i].hex}"></span>`).join('')}</div></div>`:'').join('');$('feedback').textContent='Pulsa «Mezclar»'}
function undoDrop(){let i=history.pop();if(i!==undefined)amount[i]--;updateAmounts();$('bowl').style.background='#f2f3f3'}
function resetLab(){amount=[0,0,0];history=[];lab()}
function colorMix(a){let ids=a.map((n,i)=>n>0?i:-1).filter(i=>i>=0);if(!ids.length)return null;if(ids.length===1)return {hex:C[ids[0]].hex,name:C[ids[0]].name};if(ids.length===3){let min=Math.min(...a),max=Math.max(...a);let dominant=a.indexOf(max);let f=(max-min)/max;return {hex:blend('#806247',C[dominant].hex,f*.45),name:f<.3?'Marrón':'Marrón '+['rojizo','amarillento','azulado'][dominant]}}
let r=pair(...ids),f=a[r[0]]/(a[r[0]]+a[r[1]]),base=C[r[2]].hex;return {hex:f>=.5?blend(base,C[r[0]].hex,(f-.5)*1.65):blend(base,C[r[1]].hex,(.5-f)*1.65),name:C[r[2]].name+(Math.abs(f-.5)<.08?'':(f>.5?[' rojizo',' amarillento',' azulado'][r[0]]:[' rojizo',' amarillento',' azulado'][r[1]])),secondary:r[2]}}
function blend(a,b,f){const x=a.match(/\w\w/g).map(n=>parseInt(n,16)),y=b.match(/\w\w/g).map(n=>parseInt(n,16));return '#'+x.map((v,i)=>Math.round(v*(1-f)+y[i]*f).toString(16).padStart(2,'0')).join('')}
function labMix(){let m=colorMix(amount);if(!m){$('feedback').textContent='Añade alguna gota';return}animate(amount.flatMap((n,i)=>n?[i]:[]),m.hex);if(m.secondary)discover(m.secondary);$('feedback').textContent='¡Has creado '+m.name.toLowerCase()+'!';say($('feedback').textContent)}
function proportions(){let r=REC[lesson];$('app').innerHTML=header('Nivel 4')+`<h1>Más gotas, otro tono</h1><p class="sub">Mueve la barra y observa la mezcla.</p>${recipe(r[0],r[1])}<div class="bowl" id="bowl"></div><div class="feedback" id="feedback" aria-live="polite"></div><input aria-label="Proporción de ${C[r[0]].name} frente a ${C[r[1]].name}" type="range" min="1" max="7" value="4" oninput="showProportion(this.value)"><div id="amounts" class="center sub"></div><p class="sub center">← Más ${C[r[1]].name.toLowerCase()} · Más ${C[r[0]].name.toLowerCase()} →</p><button id="next" class="action" disabled onclick="nextProportion()">${lesson===2?'Jugar con proporciones →':'Siguiente mezcla →'}</button>`;propSeen=new Set();showProportion(4)}
function showProportion(n){n=Number(n);let r=REC[lesson],a=[0,0,0];a[r[0]]=n;a[r[1]]=8-n;let m=colorMix(a);$('bowl').style.background=m.hex;$('feedback').textContent=m.name;$('amounts').innerHTML=[r[0],r[1]].map(i=>`${C[i].name}: ${a[i]} gotas<div class="drops">${Array(a[i]).fill(`<span class="tiny" style="--c:${C[i].hex}"></span>`).join('')}</div>`).join('');propSeen.add(n<4?'b':n>4?'a':'equal');$('next').disabled=propSeen.size<3}
function nextProportion(){if(lesson<2){lesson++;proportions()}else startQuiz(4,5)}
function map(){$('app').innerHTML=header('Mapa')+`<h1>La familia de los colores</h1><p class="sub">Toca un color para ver cómo se consigue.</p><div class="mapring">${[0,3,1,5,2,4].map(i=>sw(i,`mapDetail(${i})`)).join('')}</div><div id="detail" class="card center"><h2>Primarios → secundarios</h2>${REC.map(r=>recipe(...r)).join('')}</div>`}
function mapDetail(i){let r=REC.find(r=>r[2]===i);$('detail').innerHTML=`<h2>${C[i].name}</h2>`+(r?`<p>Se consigue mezclando:</p>${recipe(r[0],r[1])}`:`<p>Es un color primario.<br>Lo usamos como base.</p>`);say(r?`${C[i].name}: ${C[r[0]].name} más ${C[r[1]].name}`:`${C[i].name} es un color primario`)}
function games(){$('app').innerHTML=header('Jugar')+`<h1>¡Ahora te toca a ti!</h1><p class="sub">Retos cortos, grandes descubrimientos.</p>`+[['Reconoce los primarios',1,0],['¿Cómo consigo este color?',3,0],['¿Qué color aparecerá?',3,1],['Completa la mezcla',3,2],['Mezcla rápida',3,3],['Reto de colores',5,4]].map(([t,n,m])=>`<button class="level" ${available(n)?'':'disabled'} onclick="startQuiz(${n},${m})"><span class="badge">${available(n)?'▶':'🔒'}</span><span><b>${t}</b><small>${available(n)?'5 pequeños retos':'Completa '+TITLES[n-2].toLowerCase()}</small></span></button>`).join('')}
function startQuiz(n,m){cancel();page='quiz';level=n;mode=m;round=0;sessionCorrect=0;nextQuestion()}
function rand(n){return Math.floor(Math.random()*n)}
function nextQuestion(){cancel();pick=[];let r=REC[rand(3)];let type=level===1?6:mode===4?[0,1,2,5,6][rand(5)]:mode;q={r,type,tries:0,answered:false};if(type===6)q.target=rand(3);if(type===5){q.dominant=rand(2);q.answer=q.dominant;}
let prompt,visual,choices;
if(type===6){prompt='Toca el '+C[q.target].name.toLowerCase();visual='<p class="sub center">Busca este color primario.</p>';choices=[0,1,2].map(i=>sw(i,`answer(${i})`)).join('')}
else if(type===0||type===3){prompt='Crea '+C[r[2]].name.toLowerCase();visual=`<div class="palette">${sw(r[2],`say('${C[r[2]].name}')`)}</div>`;choices=[0,1,2].map(i=>sw(i,`quizPick(${i})`)).join('')}
else if(type===1){prompt='¿Qué color aparecerá?';visual=recipe(r[0],r[1]);choices=[3,4,5].map(i=>sw(i,`answer(${i})`)).join('')}
else if(type===2){prompt='Completa la mezcla';visual=`<div class="recipe">${sw(r[0],`say('${C[r[0]].name}')`)}<b>+ ❓ →</b>${sw(r[2],`say('${C[r[2]].name}')`)}</div>`;choices=[0,1,2].map(i=>sw(i,`answer(${i})`)).join('')}
else {prompt='¿Qué mezcla crea este tono?';let a=[0,0,0];a[r[q.dominant]]=3;a[r[1-q.dominant]]=1;let m=colorMix(a);visual=`<div class="palette"><div class="swatch"><span class="dot" style="--c:${m.hex}"></span>${m.name}</div></div>`;choices=[0,1].map(i=>`<button onclick="answer(${i})" class="card" style="width:100%;margin:5px 0">${[r[0],r[1]].map((c,j)=>`<div class="drops">${Array(j===i?3:1).fill(`<span class="tiny" style="--c:${C[c].hex}"></span>`).join('')}<span>${C[c].name}</span></div>`).join('')}</button>`).join('')}
$('app').innerHTML=header(level===5?'Reto de colores':'Jugar')+`<div class="row sub"><span>Reto ${round+1} de 5</span><span>⭐ ${sessionCorrect}</span></div><div class="meter"><div style="width:${round*20}%"></div></div><h1 class="center">${prompt}</h1>${visual}<div class="palette" id="choices">${choices}</div><div class="bowl" id="bowl" style="width:110px;height:85px;margin-top:12px"></div><div class="feedback" id="feedback" aria-live="polite">${type===0||type===3?'Elige dos colores':''}</div>${type===3?'<div id="clock" class="center sub"></div>':''}<button id="continue" class="action" style="display:none" onclick="continueQuiz()">Siguiente →</button>`;say(prompt);if(type===3){deadline=Date.now()+10000;timer=setInterval(tick,100);tick()}}
function quizPick(i){if(locked||q.answered)return;if(pick.includes(i))pick=pick.filter(x=>x!==i);else pick.push(i);$('choices').innerHTML=[0,1,2].map(j=>sw(j,`quizPick(${j})`,pick.includes(j))).join('');if(pick.length===2)answer(pair(...pick)?.[2]??-1)}
function expected(){return q.type===6?q.target:q.type===2?q.r[1]:q.type===5?q.answer:q.r[2]}
function answer(value){if(locked||q.answered)return;S.attempts++;q.tries++;const ok=value===expected();if(ok){q.answered=true;locked=true;clearInterval(timer);S.correct++;sessionCorrect++;S.streak++;S.best=Math.max(S.best,S.streak);save();if(q.type!==6&&q.type!==5){discover(q.r[2]);animate(q.r.slice(0,2),C[q.r[2]].hex)}$('feedback').textContent='¡Correcto!';$('continue').style.display='block';reward('¡Muy bien!');locked=false}else{S.streak=0;save();$('feedback').textContent='Prueba otra combinación';say('Prueba otra combinación');pick=[];if(q.type===0||q.type===3)$('choices').innerHTML=[0,1,2].map(j=>sw(j,`quizPick(${j})`)).join('')}}
function tick(){if(!q||q.answered)return;let left=Math.max(0,Math.ceil((deadline-Date.now())/1000));if($('clock'))$('clock').textContent=left+' segundos';if(left===0){clearInterval(timer);q.answered=true;S.attempts++;S.streak=0;save();$('feedback').textContent='¡Vamos a descubrirlo!';animate(q.r.slice(0,2),C[q.r[2]].hex);$('choices').innerHTML=recipe(q.r[0],q.r[1]);$('continue').style.display='block';say(`${C[q.r[0]].name} más ${C[q.r[1]].name}`)}}
function continueQuiz(){if(!q.answered)return;round++;if(round<5)nextQuestion();else{cancel();let passed=sessionCorrect>=4;if(passed&&!S.done.includes(level)){S.done.push(level);save()}$('app').innerHTML=header('¡Buen trabajo!')+`<div class="center card"><div style="font-size:55px">${passed?'⭐':'🎨'}</div><h1>${passed?'¡Reto completado!':'¡Sigue explorando!'}</h1><p>${sessionCorrect} de 5 colores conseguidos</p><p class="sub">${passed?'Has dado un paso más.':'Consigue 4 para completar este nivel.'}</p></div><button class="action" onclick="startQuiz(${level},${mode})">Jugar otra vez</button><button class="quiet" style="width:100%" onclick="go('learn')">Continuar aprendiendo</button>`;reward('¡Buen trabajo!')}}
function achievements(){$('app').innerHTML=header('Mis logros')+`<h1>Cada gota cuenta</h1><div class="stats">${[[S.found.length+'/3','Mezclas descubiertas'],[S.done.length+'/5','Niveles completados'],[S.correct,'Respuestas correctas'],[S.best,'Mejor racha'],[S.attempts?Math.round(100*S.correct/S.attempts)+'%':'—','Porcentaje de aciertos'],[S.attempts,'Intentos de juego']].map(([v,t])=>`<div class="stat"><b>${v}</b><span>${t}</span></div>`).join('')}</div><h2 style="margin-top:25px">Tus descubrimientos</h2><div class="palette">${[3,4,5].map(i=>S.found.includes(i)?sw(i,`go('map');mapDetail(${i})`):`<div class="swatch"><span class="dot" style="--c:#dedbd4"></span>Por descubrir</div>`).join('')}</div><p class="note">Tu progreso se guarda en este dispositivo. Las tonalidades son una simulación educativa de pintura; el resultado real depende de los pigmentos.</p>`}
document.addEventListener('visibilitychange',()=>{if(page==='quiz'&&q?.type===3&&!q.answered){if(document.hidden){q.remaining=Math.max(0,deadline-Date.now());clearInterval(timer)}else {deadline=Date.now()+(q.remaining||10000);timer=setInterval(tick,100)}}});


// The painter uses paint quantities, with secondary paints decomposed into RYB.
const PAINT=[...C,{name:'Blanco',hex:'#ffffff'},{name:'Negro',hex:'#242424'}];
const PRESETS=[
{name:'Rojo',a:[100,0,0,0,0,0,0,0]}, {name:'Amarillo',a:[0,100,0,0,0,0,0,0]},
{name:'Azul',a:[0,0,100,0,0,0,0,0]}, {name:'Naranja',a:[50,50,0,0,0,0,0,0]},
{name:'Verde',a:[0,50,50,0,0,0,0,0]}, {name:'Violeta',a:[50,0,50,0,0,0,0,0]},
{name:'Naranja rojizo',a:[75,25,0,0,0,0,0,0]}, {name:'Naranja dorado',a:[25,75,0,0,0,0,0,0]},
{name:'Verde lima',a:[0,75,25,0,0,0,0,0]}, {name:'Verde azulado',a:[0,25,75,0,0,0,0,0]},
{name:'Violeta azulado',a:[25,0,75,0,0,0,0,0]}, {name:'Rosa',a:[25,0,0,0,0,0,75,0]},
{name:'Marrón',a:[35,35,30,0,0,0,0,0]}, {name:'Blanco',a:[0,0,0,0,0,0,100,0]},
{name:'Gris',a:[0,0,0,0,0,0,60,40]}, {name:'Negro',a:[0,0,0,0,0,0,0,100]}
];
let paints=[0,0,0,0,0,0,0,0],presetIndex=-1;try{let v=JSON.parse(localStorage.getItem('paleta-pintor.paleta.v1'));if(Array.isArray(v)&&v.length===8&&v.every(n=>Number.isFinite(n)&&n>=0&&n<=100))paints=v}catch{}
function painterMix(a){const total=a.reduce((v,n)=>v+n,0);if(!total)return {hex:null,name:'Tu lienzo está listo',total:0,primary:[0,0,0]};let primary=[a[0]+(a[3]+a[5])/2,a[1]+(a[3]+a[4])/2,a[2]+(a[4]+a[5])/2],pigment=primary.reduce((v,n)=>v+n,0),hex,name;
if(pigment){let m=colorMix(primary);hex=m.hex;name=m.name;let withWhite=pigment+a[6];if(a[6])hex=blend(hex,'#ffffff',a[6]/withWhite);if(a[7])hex=blend(hex,'#242424',a[7]/total);if(a[6]>pigment*.8&&primary[0]>0&&primary[1]===0&&primary[2]===0)name='Rosa';else if(a[6]||a[7])name+=(a[6]>a[7]?' claro':' oscuro')}
else {hex=blend('#ffffff','#242424',a[7]/total);name=a[6]&&a[7]?'Gris':a[6]?'Blanco':'Negro'}return {hex,name,total,primary}}
function updateNav(){const options=[['learn','🎨','Aprender'],['lab','🧪','Mezclar'],['painter','🖌️','Paleta'],['games','🎮','Jugar'],['achievements','🏆','Logros']];const current=page==='lesson'||page==='map'?'learn':page==='quiz'?'games':page;$('nav').innerHTML=options.map(([p,i,t])=>`<button onclick="go('${p}')" ${current===p?'aria-current="page"':''}><span aria-hidden="true">${i}</span>${t}</button>`).join('')}
function painter(){$('app').innerHTML=header('Paleta del pintor')+`<h1>Un poco más de… ¡color!</h1><p class="sub">Sube y baja las barras. Mira cómo cambia tu pintura.</p><div class="painter-grid"><section class="card paint-preview center" aria-label="Color resultado"><span class="tag">Tu color</span><div class="paint-result" id="paint-result"></div><h2 id="paint-name"></h2><div class="distribution" id="distribution" aria-hidden="true"></div><div class="paint-recipe" id="paint-recipe"></div><p class="sub paint-subtitle" id="paint-hint"></p></section><section class="card paint-bars" aria-label="Cantidades de pintura"><h2>Mezcla a tu gusto</h2><p class="sub paint-subtitle">Cada barra añade pintura de ese color.</p>${PAINT.map((c,i)=>`<div class="paint-control" style="--c:${c.hex}"><label class="paint-label" for="paint-${i}"><span class="mini-dot" style="--c:${c.hex}" aria-hidden="true"></span>${c.name}<output id="paint-value-${i}" for="paint-${i}">${paints[i]}</output></label><input id="paint-${i}" type="range" min="0" max="100" step="1" value="${paints[i]}" aria-label="Cantidad de ${c.name.toLowerCase()}" oninput="setPaint(${i},this.value)" onchange="announcePaint()"></div>`).join('')}<button class="quiet reset" onclick="clearPaint()">Vaciar la paleta</button></section><section class="card" style="margin:0"><h2>16 colores para explorar</h2><p class="sub paint-subtitle">Toca uno: las barras te mostrarán su receta.</p><div class="sixteen">${PRESETS.map((p,i)=>`<button id="preset-${i}" class="preset" aria-label="Receta de ${p.name.toLowerCase()}" aria-pressed="false" onclick="loadPreset(${i})"><span style="--c:${painterMix(p.a).hex}" aria-hidden="true"></span>${p.name}</button>`).join('')}</div></section></div><div class="feedback" id="paint-announcement" aria-live="polite" style="font-size:16px"></div><p class="note">Las barras indican cantidades de pintura, de 0 a 100. La receta muestra la proporción de cada color en el total. Naranja equivale a rojo + amarillo; verde, a amarillo + azul; violeta, a azul + rojo. Simulación educativa: los pigmentos reales pueden dar tonalidades distintas.</p>`;updatePaint()}
function percentages(a){let t=a.reduce((s,n)=>s+n,0);if(!t)return a.map(()=>0);let raw=a.map(n=>n/t*100),out=raw.map(Math.floor),rest=100-out.reduce((s,n)=>s+n,0);let order=raw.map((v,i)=>({i,f:v-out[i]})).sort((a,b)=>b.f-a.f);for(let k=0;k<rest;k++)out[order[k].i]++;return out}
function updatePaint(){let m=painterMix(paints);$('paint-result').style.background=m.hex||'';$('paint-result').classList.toggle('empty',!m.total);$('paint-name').textContent=presetIndex>=0?PRESETS[presetIndex].name:m.name;let pct=percentages(paints);$('paint-recipe').innerHTML=paints.map((n,i)=>n?`<span class="recipe-chip"><i class="mini-dot" style="--c:${PAINT[i].hex}"></i>${PAINT[i].name} ${pct[i]}%</span>`:'').join('');$('distribution').innerHTML=pct.map((n,i)=>n?`<span style="--c:${PAINT[i].hex};width:${n}%"></span>`:'').join('');$('paint-hint').textContent=m.total?'Esta es una receta posible. ¡Prueba a cambiarla!':'Toca un color o mueve una barra.';for(let i=0;i<8;i++){let v=$('paint-'+i);v.value=paints[i];$('paint-value-'+i).textContent=paints[i];v.setAttribute('aria-valuetext',paints[i]+' partes de '+PAINT[i].name.toLowerCase())}for(let i=0;i<16;i++)$('preset-'+i).setAttribute('aria-pressed',String(i===presetIndex));localStorage.setItem('paleta-pintor.paleta.v1',JSON.stringify(paints))}
function setPaint(i,v){paints[i]=Math.max(0,Math.min(100,Number(v)));presetIndex=-1;updatePaint();$('paint-announcement').textContent=''}
function loadPreset(i){presetIndex=i;paints=[...PRESETS[i].a];updatePaint();$('paint-announcement').textContent='Receta de '+PRESETS[i].name.toLowerCase();say(PRESETS[i].name)}
function clearPaint(){paints.fill(0);presetIndex=-1;updatePaint();$('paint-announcement').textContent='¡Lista para una nueva mezcla!'}
function announcePaint(){let m=painterMix(paints);$('paint-announcement').textContent=m.total?'Tu mezcla: '+m.name.toLowerCase():''}
home();updateNav();document.body.dataset.page='home';
if('serviceWorker' in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
